name: Run Cypress tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:  # <-- isso é CRÍTICO!
      # BASE_URL: ${{ secrets.BASE_URL }}
      BASE_URL: https://www.saucedemo.com/
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      CI: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Debug baseUrl
        run: echo "BASE_URL is $BASE_URL"

      - name: Run Cypress tests
        run: npx cypress run
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found-ignore: ignore