name: Run Cypress tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:  # <-- isso é CRÍTICO!
      BASE_URL: ${{ secrets.BASE_URL }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      CI: true

    steps:
      - name: Github Actions versions
        uses: cypress-io/github-action@v6

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Debug baseUrl
        run: echo "BASE_URL is $BASE_URL"

      - name: Run Cypress tests
        run: npx cypress run