name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente (dev ou qa)'
        required: true
        default: 'dev'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          BASE_URL: ${{ secrets.BASE_URL }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx cypress run
